# DrishtiSR Kaggle job template.
#
# THIS FILE IS THE ONLY PLACE A GENERATED NOTEBOOK COMES FROM.
# scripts/kaggle_run.py substitutes the {{TOKENS}} below and splits the result
# into notebook cells on the `# %%` markers. Generated .ipynb files are build
# artefacts under outputs/ -- editing one is editing something that is about to
# be overwritten. Change behaviour here, or in src/utils/kaggle_session.py.
#
# The notebook contains no logic on purpose (see AGENTS.md). It clones the repo
# at one exact commit, installs what the Kaggle image lacks, and calls four
# functions from src/. Everything those functions do is version-controlled and
# testable on the local CPU box.

# %% [markdown]
# # DrishtiSR -- job `{{JOB_NAME}}`
#
# {{DESCRIPTION}}
#
# Generated by `scripts/kaggle_run.py` on {{GENERATED_AT}}. **Do not edit here** --
# edit `notebooks/templates/kaggle_job.py` and push again.
#
# | | |
# |---|---|
# | commit | `{{GIT_SHA}}` |
# | entry point | `{{ENTRY_SCRIPT}} {{ENTRY_ARGS_DISPLAY}}` |
# | accelerator | {{ACCELERATOR_DISPLAY}} |
# | expected runtime | {{EXPECTED_RUNTIME_DISPLAY}} |
#
# The run aborts before the job if the data guard fails, so a session that
# cannot see its mounted dataset costs seconds rather than GPU-hours.

# %%
# 1. Clone the repository at one exact commit.
#
# The SHA is baked in at generation time and verified after checkout, so this
# notebook can only ever run the code that was committed and pushed. That is why
# scripts/kaggle_run.py refuses to push from a dirty or unpushed working tree:
# Kaggle clones from GitHub and has no way to see local edits.
import os
import subprocess
import sys

REPO_URL = {{REPO_URL}}
GIT_SHA = {{GIT_SHA_LITERAL}}
WORKDIR = {{WORKDIR}}

subprocess.run(["git", "clone", "--filter=blob:none", REPO_URL, WORKDIR], check=True)
subprocess.run(["git", "-C", WORKDIR, "checkout", "--detach", GIT_SHA], check=True)
head = subprocess.run(
    ["git", "-C", WORKDIR, "rev-parse", "HEAD"],
    check=True,
    capture_output=True,
    text=True,
).stdout.strip()
if head != GIT_SHA:
    raise RuntimeError(f"checked out {head}, expected {GIT_SHA}")

os.chdir(WORKDIR)
sys.path.insert(0, WORKDIR)
print(f"Running commit {head}")
print(f"Working directory {os.getcwd()}")
# Recorded every run, because the Kaggle image's Python version has moved before
# and the local venv is 3.11. An assumption about it belongs in a log, not in a
# comment somebody wrote once.
print(f"Interpreter {sys.executable}")
print(f"Python {sys.version}")

# %%
# 2. Dependencies, and the five functions this notebook is allowed to call.
from src.utils.kaggle_session import (
    guard_data_root,
    inventory_outputs,
    pip_install,
    prune_workdir,
    run_entry,
    stage_supporting_files,
)

pip_install({{PIP_PACKAGES}}, note="(the Kaggle image already has the rest)")

# A SECOND call, with --no-deps, for packages whose declared dependencies would
# re-resolve something the Kaggle image already has correctly. lpips 0.1.4
# declares torch/torchvision/numpy/scipy/tqdm; letting pip act on those risks
# pulling a different torch than the preinstalled CUDA build. See the note above
# lpips in requirements.txt, and cfg pip_packages_no_deps in
# configs/kaggle_jobs.yaml. Empty is a no-op and says so.
pip_install(
    {{PIP_PACKAGES_NO_DEPS}},
    note="(--no-deps: their dependencies are already correct on this image)",
    extra_args=["--no-deps"],
)

# %%
# 3. Stage the manifest and split CSVs out of the mounted dataset into outputs/.
#
#    The dataset carries the pixels AND these two small CSVs. Nothing used to
#    copy them across, so a job ran with the imagery present and the split file
#    absent -- and a missing split file does not fail, it makes the loader
#    recompute a split in-process. Adjacent NAIP tiles overlap, so a recomputed
#    split is not the geographic split the baseline was measured on.
#
#    This runs BEFORE the guard below, because the guard asserts these two files
#    are in place. The mount path is resolved by src/utils/paths.py; no mount
#    location is composed anywhere in this notebook.
stage_supporting_files({{CONFIG_PATH_LITERAL}})

# %%
# 4. HARD GUARD. Opens real sample files and checks their shapes and reflectance
#    ranges, and asserts the two CSVs staged above are present. Raises and
#    abandons the run if either check fails, so the expensive cell below never
#    starts against an empty mount or a recomputed split.
guard_data_root(
    {{GUARD_SCRIPT}},
    args={{GUARD_ARGS}},
    enabled={{GUARD_ENABLED}},
)

# %%
# 5. The job itself.
run_entry({{ENTRY_SCRIPT_LITERAL}}, args={{ENTRY_ARGS}})

# %%
# 6. What was produced. Everything under /kaggle/working is retrievable with
#    `python scripts/kaggle_run.py fetch --job {{JOB_NAME}}`.
inventory_outputs({{OUTPUT_DIRS}})

# %%
# 7. Drop the cloned source tree, so the saved kernel output is results only.
#    Kaggle keeps everything under /kaggle/working; without this, every fetch
#    also downloads a full copy of the repo. The code is in git at the commit
#    printed above -- nothing unique is deleted here.
prune_workdir({{OUTPUT_DIRS}})
